import time

def namesday_fi():

    today = time.strftime("%d-%m", time.localtime())
    month = time.strftime("%m", time.localtime())

    if month == '01':
        if today == '01-01': names_day = 'Uudenvuodenp&auml;iv&auml; '
        elif today == '02-01': names_day = 'Aapeli'
        elif today == '03-01': names_day = 'Elmeri, Elmer, Elmo'
        elif today == '04-01': names_day = 'Ruut'
        elif today == '05-01': names_day = 'Lea, Leea'
        elif today == '06-01': names_day = 'Harri'
        elif today == '07-01': names_day = 'Aukusti, Aku, August'
        elif today == '08-01': names_day = 'Hilppa, Titta'
        elif today == '09-01': names_day = 'Veikko, Veli, Veijo, Veikka'
        elif today == '10-01': names_day = 'Nyyrikki'
        elif today == '11-01': names_day = 'Kari, Karri'
        elif today == '12-01': names_day = 'Toini'
        elif today == '13-01': names_day = 'Nuutti'
        elif today == '14-01': names_day = 'Sakari'
        elif today == '15-01': names_day = 'Solja'
        elif today == '16-01': names_day = 'Ilmari, Ilmo'
        elif today == '17-01': names_day = 'Toni, Anttoni, Antto, Anton'
        elif today == '18-01': names_day = 'Laura'
        elif today == '19-01': names_day = 'Heikki, Henrik, Henrikki, Henri'
        elif today == '20-01': names_day = 'Henna, Henni, Henriikka'
        elif today == '21-01': names_day = 'Aune, Oona, Netta, Auni'
        elif today == '22-01': names_day = 'Visa'
        elif today == '23-01': names_day = 'Eine, Eini, Ensi'
        elif today == '24-01': names_day = 'Senja'
        elif today == '25-01': names_day = 'Paavo, Pauli, Paavali, Paul'
        elif today == '26-01': names_day = 'Joonatan'
        elif today == '27-01': names_day = 'Viljo'
        elif today == '28-01': names_day = 'Kaarlo, Kalle, Kaarle, Mies'
        elif today == '29-01': names_day = 'Valtteri'
        elif today == '30-01': names_day = 'Irja'
        elif today == '31-01': names_day = 'Alli'

    elif month == '02':
        if today == '01-02': names_day = 'Riitta'
        elif today == '02-02': names_day = 'Aamu, Jemina'
        elif today == '03-02': names_day = 'Valo'
        elif today == '04-02': names_day = 'Armi, Ronja'
        elif today == '05-02': names_day = 'Asser'
        elif today == '06-02': names_day = 'Terhi, Teija, Tiia, Tea, Terhikki'
        elif today == '07-02': names_day = 'Riku, Rikhard'
        elif today == '08-02': names_day = 'Laina'
        elif today == '09-02': names_day = 'Raija, Raisa'
        elif today == '10-02': names_day = 'Elina, Elna, Ella, Ellen'
        elif today == '11-02': names_day = 'Elina, Elna, Ella, Ellen'
        elif today == '12-02': names_day = 'Elma, Elmi'
        elif today == '13-02': names_day = 'Sulo, Sulho'
        elif today == '14-02': names_day = 'Voitto, Valentin, Tino'
        elif today == '15-02': names_day = 'Sipi, Sippo'
        elif today == '16-02': names_day = 'Kai'
        elif today == '17-02': names_day = 'V&auml;in&ouml;, V&auml;in&auml;m&ouml;'
        elif today == '18-02': names_day = 'Kaino'
        elif today == '19-02': names_day = 'Eija'
        elif today == '20-02': names_day = 'Heli, Helin&auml;, Helj&auml;, Hely'
        elif today == '21-02': names_day = 'Keijo'
        elif today == '22-02': names_day = 'Tuulikki, Tuuli, Tuulia'
        elif today == '23-02': names_day = 'Aslak'
        elif today == '24-02': names_day = 'Matti, Matias'
        elif today == '25-02': names_day = 'Tuija, Tuire'
        elif today == '26-02': names_day = 'Nestori'
        elif today == '27-02': names_day = 'Torsti'
        elif today == '28-02': names_day = 'Onni'
        elif today == '29-02': names_day = 'Karkausp&auml;iv&auml;'

    elif month == '03':
        if today == '01-03': names_day = 'Alpo, Alvi, Alpi'
        elif today == '02-03': names_day = 'Virve, Virva'
        elif today == '03-03': names_day = 'Kauko'
        elif today == '04-03': names_day = 'Ari, Arsi, Atro'
        elif today == '05-03': names_day = 'Laila, Leila'
        elif today == '06-03': names_day = 'Tarmo'
        elif today == '07-03': names_day = 'Tarja, Taru'
        elif today == '08-03': names_day = 'Vilppu'
        elif today == '09-03': names_day = 'Auvo'
        elif today == '10-03': names_day = 'Aurora, Aura, Auri'
        elif today == '11-03': names_day = 'Kalervo'
        elif today == '12-03': names_day = 'Reijo, Reko'
        elif today == '13-03': names_day = 'Erno, Tarvo, Ernesti'
        elif today == '14-03': names_day = 'Matilda, Tilda'
        elif today == '15-03': names_day = 'Risto'
        elif today == '16-03': names_day = 'Ilkka'
        elif today == '17-03': names_day = 'Kerttu, Kerttuli'
        elif today == '18-03': names_day = 'Eetu, Edvard'
        elif today == '19-03': names_day = 'Jooseppi, Juuso, Joosef, Josefiina'
        elif today == '20-03': names_day = 'Aki, Joakim, Kim, Jaakkima'
        elif today == '21-03': names_day = 'Pentti'
        elif today == '22-03': names_day = 'Vihtori'
        elif today == '23-03': names_day = 'Akseli'
        elif today == '24-03': names_day = 'Kaapo, Gabriel, Kaapro, Kaappo'
        elif today == '25-03': names_day = 'Aija'
        elif today == '26-03': names_day = 'Manu, Immanuel, Manne, Immo'
        elif today == '27-03': names_day = 'Sauli, Saul'
        elif today == '28-03': names_day = 'Armas'
        elif today == '29-03': names_day = 'Joonas, Jouni, Joni, Joona, Jonne, Jonni'
        elif today == '30-03': names_day = 'Usko'
        elif today == '31-03': names_day = 'Irma, Irmeli'

    elif month == '04':
        if today == '01-04': names_day = 'Raita, Pulmu'
        elif today == '02-04': names_day = 'Pellervo'
        elif today == '03-04': names_day = 'Sampo, Veeti'
        elif today == '04-04': names_day = 'Ukko'
        elif today == '05-04': names_day = 'Irene, Irina, Ira, Iro'
        elif today == '06-04': names_day = 'Vilho, Ville, Viljami, Vilhelm, Vili, Jami '
        elif today == '07-04': names_day = 'Allan, Ahvo'
        elif today == '08-04': names_day = 'Suoma, Suometar'
        elif today == '09-04': names_day = 'Elias, Eelis, Eeli, Eljas'
        elif today == '10-04': names_day = 'Tero'
        elif today == '11-04': names_day = 'Verna'
        elif today == '12-04': names_day = 'Julia, Julius, Juliaana, Janna'
        elif today == '13-04': names_day = 'Tellervo'
        elif today == '14-04': names_day = 'Taito'
        elif today == '15-04': names_day = 'Linda, Tuomi'
        elif today == '16-04': names_day = 'Jalo, Patrik'
        elif today == '17-04': names_day = 'Otto'
        elif today == '18-04': names_day = 'Valto, Valdemar'
        elif today == '19-04': names_day = 'P&auml;lvi, Pilvi'
        elif today == '20-04': names_day = 'Lauha'
        elif today == '21-04': names_day = 'Anssi, Anselmi'
        elif today == '22-04': names_day = 'Alina'
        elif today == '23-04': names_day = 'Yrj&ouml;, Jyrki, Jyri, Yrj&auml;n&auml;, Jori'
        elif today == '24-04': names_day = 'Pertti, Albert, Altti'
        elif today == '25-04': names_day = 'Markku, Markus, Marko'
        elif today == '26-04': names_day = 'Terttu, Teresa'
        elif today == '27-04': names_day = 'Merja'
        elif today == '28-04': names_day = 'Ilpo, Ilppo, Tuure'
        elif today == '29-04': names_day = 'Teijo'
        elif today == '30-04': names_day = 'Mirja, Mirva, Mira, Miia, Mirjami, Mirka, Mirkka'

    elif month == '05':
        if today == '01-05': names_day = 'Vappu, Valpuri'
        elif today == '02-05': names_day = 'Vuokko, Viivi'
        elif today == '03-05': names_day = 'Outi'
        elif today == '04-05': names_day = 'Ruusu, Roosa'
        elif today == '05-05': names_day = 'Maini'
        elif today == '06-05': names_day = 'Ylermi'
        elif today == '07-05': names_day = 'Helmi, Kastehelmi'
        elif today == '08-05': names_day = 'Heino'
        elif today == '09-05': names_day = 'Timo'
        elif today == '10-05': names_day = 'Aino, Aina, Aini, Ainikki'
        elif today == '11-05': names_day = 'Osmo'
        elif today == '12-05': names_day = 'Lotta'
        elif today == '13-05': names_day = 'Kukka, Floora'
        elif today == '14-05': names_day = 'Tuula'
        elif today == '15-05': names_day = 'Sofia, Sonja, Sohvi'
        elif today == '16-05': names_day = 'Esteri, Essi, Ester'
        elif today == '17-05': names_day = 'Maila, Maili, Mailis, Rebekka'
        elif today == '18-05': names_day = 'Erkki, Eero, Eerik, Eerika, Eerikki'
        elif today == '19-05': names_day = 'Emilia, Emma, Emmi, Milla, Milja, Milka, Amalia'
        elif today == '20-05': names_day = 'Lilja, Karoliina, Lilli'
        elif today == '21-05': names_day = 'Kosti, Konsta, Konstantin'
        elif today == '22-05': names_day = 'Hemminki, Hemmo'
        elif today == '23-05': names_day = 'Lyydia, Lyyli'
        elif today == '24-05': names_day = 'Tuukka, Touko'
        elif today == '25-05': names_day = 'Urpo'
        elif today == '26-05': names_day = 'Vilhelmiina, Minna, Vilma, Miina, Mimmi'
        elif today == '27-05': names_day = 'Ritva'
        elif today == '28-05': names_day = 'Alma'
        elif today == '29-05': names_day = 'Oiva, Oliver, Olivia, Oivi'
        elif today == '30-05': names_day = 'Pasi'
        elif today == '31-05': names_day = 'Helka, Helga'

    elif month == '06':
        if today == '01-06': names_day = 'Teemu, Nikodemus'
        elif today == '02-06': names_day = 'Venla'
        elif today == '03-06': names_day = 'Orvokki, Viola'
        elif today == '04-06': names_day = 'Toivo'
        elif today == '05-06': names_day = 'Sulevi'
        elif today == '06-06': names_day = 'Kustaa, Ky&ouml;sti, Kustavi'
        elif today == '07-06': names_day = 'Suvi, Robert, Roope'
        elif today == '08-06': names_day = 'Salomo, Salomon'
        elif today == '09-06': names_day = 'Ensio'
        elif today == '10-06': names_day = 'Seppo'
        elif today == '11-06': names_day = 'Impi, Immi'
        elif today == '12-06': names_day = 'Esko'
        elif today == '13-06': names_day = 'Raili, Raila'
        elif today == '14-06': names_day = 'Kielo, Pihla'
        elif today == '15-06': names_day = 'Vieno, Moona, Viena'
        elif today == '16-06': names_day = 'P&auml;ivi, P&auml;ivikki, P&auml;iv&auml;'
        elif today == '17-06': names_day = 'Urho'
        elif today == '18-06': names_day = 'Tapio'
        elif today == '19-06': names_day = 'Siiri'
        elif today == '20-06': names_day = 'Into'
        elif today == '21-06': names_day = 'Ahti, Ahto'
        elif today == '22-06': names_day = 'Paula, Liina, Pauliina'
        elif today == '23-06': names_day = 'Aatto, Aatu, Aadolf'
        elif today == '24-06': names_day = 'Johannes, Juhani, Juha, Juho, Jukka, Jussi, Janne, Jani, Juhana'
        elif today == '25-06': names_day = 'Uuno'
        elif today == '26-06': names_day = 'Jorma, Jarmo, Jarkko, Jarno, Jere, Jeremias'
        elif today == '27-06': names_day = 'Elviira, Elvi'
        elif today == '28-06': names_day = 'Leo'
        elif today == '29-06': names_day = 'Pietari, Pekka, Petri, Petra, Petteri, Pekko'
        elif today == '30-06': names_day = 'P&auml;ivi&ouml;, P&auml;iv&ouml;'

    elif month == '07':
        if today == '01-07': names_day = 'Aaro, Aaron'
        elif today == '02-07': names_day = 'Maria, Mari, Maija, Meeri, Maaria, Marika, Maiju, Maikki, Kukka-Maari'
        elif today == '03-07': names_day = 'Arvo'
        elif today == '04-07': names_day = 'Ulla, Ulpu'
        elif today == '05-07': names_day = 'Unto, Untamo'
        elif today == '06-07': names_day = 'Esa, Esaias'
        elif today == '07-07': names_day = 'Klaus, Launo'
        elif today == '08-07': names_day = 'Turo, Turkka'
        elif today == '09-07': names_day = 'Ilta, Jasmin'
        elif today == '10-07': names_day = 'Saima, Saimi'
        elif today == '11-07': names_day = 'Elli, Noora, Nelli, Eleonoora'
        elif today == '12-07': names_day = 'Hermanni, Herkko, Herman'
        elif today == '13-07': names_day = 'Ilari, Lari, Joel'
        elif today == '14-07': names_day = 'Aliisa, Alisa'
        elif today == '15-07': names_day = 'Rauni, Rauna'
        elif today == '16-07': names_day = 'Reino'
        elif today == '17-07': names_day = 'Ossi, Ossian'
        elif today == '18-07': names_day = 'Riikka'
        elif today == '19-07': names_day = 'Saara, Sari, Salli, Salla, Sara'
        elif today == '20-07': names_day = 'Marketta, Maarit, Reeta, Maaret, Reetta, Margareeta'
        elif today == '21-07': names_day = 'Johanna, Hanna, Jenni, Jonna, Jenna, Hannele, Hanne, Joanna'
        elif today == '22-07': names_day = 'Leena, Leeni, Lenita, Matleena'
        elif today == '23-07': names_day = 'Oili, Olga'
        elif today == '24-07': names_day = 'Kristiina, Kirsti, Tiina, Kirsi, Krista, Kiia'
        elif today == '25-07': names_day = 'Jaakko, Jaakoppi, Jimi, Jaakoppi'
        elif today == '26-07': names_day = 'Martta'
        elif today == '27-07': names_day = 'Heidi'
        elif today == '28-07': names_day = 'Atso'
        elif today == '29-07': names_day = 'Olavi, Olli, Uolevi, Uoti'
        elif today == '30-07': names_day = 'Asta'
        elif today == '31-07': names_day = 'Helena, Elena'
    
    elif month == '08':
        if today == '01-08': names_day = 'Maire'
        elif today == '02-08': names_day = 'Kimmo'
        elif today == '03-08': names_day = 'Nea, Linnea, Neea, Vanamo'
        elif today == '04-08': names_day = 'Veera'
        elif today == '05-08': names_day = 'Salme, Sanelma'
        elif today == '06-08': names_day = 'Toimi, Keimo'
        elif today == '07-08': names_day = 'Lahja'
        elif today == '08-08': names_day = 'Sylvi, Sylvia, Silva'
        elif today == '09-08': names_day = 'Erja, Eira'
        elif today == '10-08': names_day = 'Lauri, Lasse, Lassi'
        elif today == '11-08': names_day = 'Sanna, Sanni, Susanna, Susanne'
        elif today == '12-08': names_day = 'Klaara'
        elif today == '13-08': names_day = 'Jesse'
        elif today == '14-08': names_day = 'Onerva, Kanerva'
        elif today == '15-08': names_day = 'Marjatta, Marja, Jaana, Marjo, Marjut, Marjaana, Marjukka, Marita, Maritta, Marianne, Marianna'
        elif today == '17-08': names_day = 'Verneri'
        elif today == '18-08': names_day = 'Leevi'
        elif today == '19-08': names_day = 'Mauno, Maunu'
        elif today == '20-08': names_day = 'Samuli, Sami, Samuel, Samu'
        elif today == '21-08': names_day = 'Soini, Veini'
        elif today == '22-08': names_day = 'Iivari, Iivo'
        elif today == '23-08': names_day = 'Varma, Signe'
        elif today == '24-08': names_day = 'Perttu'
        elif today == '25-08': names_day = 'Loviisa'
        elif today == '26-08': names_day = 'Ilma, Ilmi, Ilmatar'
        elif today == '27-08': names_day = 'Rauli'
        elif today == '28-08': names_day = 'Tauno'
        elif today == '29-08': names_day = 'Iines, Iina, Inari'
        elif today == '30-08': names_day = 'Eemil, Eemeli'
        elif today == '31-08': names_day = 'Arvi'

    elif month == '09':
        if today == '01-09': names_day = 'Pirkka'
        elif today == '02-09': names_day = 'Sinikka, Sini'
        elif today == '03-09': names_day = 'Soili, Soile, Soila'
        elif today == '04-09': names_day = 'Ansa'
        elif today == '05-09': names_day = 'Roni, Mainio'
        elif today == '06-09': names_day = 'Asko'
        elif today == '07-09': names_day = 'Miro, Arho, Arhippa'
        elif today == '08-09': names_day = 'Taimi'
        elif today == '09-09': names_day = 'Eevert, Isto'
        elif today == '10-09': names_day = 'Kalevi, Kaleva'
        elif today == '11-09': names_day = 'Aleksanteri, Santeri, Santtu, Ali, Ale, Aleksandra'
        elif today == '12-09': names_day = 'Valma, Vilja'
        elif today == '13-09': names_day = 'Orvo'
        elif today == '14-09': names_day = 'Iida'
        elif today == '15-09': names_day = 'Sirpa'
        elif today == '16-09': names_day = 'Hellevi, Hillevi, Hille, Hilla'
        elif today == '17-09': names_day = 'Aili, Aila'
        elif today == '18-09': names_day = 'Tyyne, Tytti, Tyyni'
        elif today == '19-09': names_day = 'Reija'
        elif today == '20-09': names_day = 'Varpu, Vaula'
        elif today == '21-09': names_day = 'Mervi'
        elif today == '22-09': names_day = 'Mauri'
        elif today == '23-09': names_day = 'Mielikki'
        elif today == '24-09': names_day = 'Alvar, Auno'
        elif today == '25-09': names_day = 'Kullervo'
        elif today == '26-09': names_day = 'Kuisma'
        elif today == '27-09': names_day = 'Vesa'
        elif today == '28-09': names_day = 'Arja'
        elif today == '29-09': names_day = ' Mikko, Mika, Mikael, Miika, Miikka, Miska, Miko, Mikaela'
        elif today == '30-09': names_day = 'Sorja, Sirja'

    elif month == '10':
        if today == '01-10': names_day = 'Rauno, Rainer, Raine, Raino'
        elif today == '02-10': names_day = 'Valio'
        elif today == '03-10': names_day = 'Raimo'
        elif today == '04-10': names_day = 'Saila, Saija'
        elif today == '05-10': names_day = 'Inkeri, Inka'
        elif today == '06-10': names_day = 'Minttu, Pinja'
        elif today == '07-10': names_day = 'Pirkko, Pirjo, Piritta, Pirita, Birgitta'
        elif today == '08-10': names_day = 'Hilja'
        elif today == '09-10': names_day = 'Ilona'
        elif today == '10-10': names_day = 'Aleksi, Aleksis'
        elif today == '11-10': names_day = 'Otso, Ohto'
        elif today == '12-10': names_day = 'Aarre, Aarto'
        elif today == '13-10': names_day = 'Taina, Tanja, Taija'
        elif today == '14-10': names_day = 'Elsa, Else, Elsi'
        elif today == '15-10': names_day = 'Helvi, Heta'
        elif today == '16-10': names_day = 'Sirkka, Sirkku'
        elif today == '17-10': names_day = 'Saini, Saana'
        elif today == '18-10': names_day = 'Satu, S&auml;de'
        elif today == '19-10': names_day = 'Uljas'
        elif today == '20-10': names_day = 'Kauno, Kasperi'
        elif today == '21-10': names_day = 'Ursula'
        elif today == '22-10': names_day = 'Anja, Anita, Anniina, Anitta'
        elif today == '23-10': names_day = 'Severi'
        elif today == '24-10': names_day = 'Asmo, Rasmus'
        elif today == '25-10': names_day = 'Sointu'
        elif today == '26-10': names_day = 'Niina, Nina, Amanda, Manta'
        elif today == '27-10': names_day = 'Helli, Hell&auml;, Hellin, Helle'
        elif today == '28-10': names_day = 'Simo'
        elif today == '29-10': names_day = 'Alfred, Urmas'
        elif today == '30-10': names_day = 'Eila'
        elif today == '31-10': names_day = 'Artturi, Arto, Arttu'

    elif month == '11':
        if today == '01-11': names_day = 'Pyry, Lyly'
        elif today == '02-11': names_day = 'Topi, Topias'
        elif today == '03-11': names_day = 'Terho'
        elif today == '04-11': names_day = 'Hertta'
        elif today == '05-11': names_day = 'Reima'
        elif today == '06-11': names_day = 'Kustaa Aadolf '
        elif today == '07-11': names_day = 'Taisto'
        elif today == '08-11': names_day = 'Aatos'
        elif today == '09-11': names_day = 'Teuvo'
        elif today == '10-11': names_day = 'Martti'
        elif today == '11-11': names_day = 'Panu'
        elif today == '12-11': names_day = 'Virpi'
        elif today == '13-11': names_day = 'Ano, Kristian'
        elif today == '14-11': names_day = 'Iiris'
        elif today == '15-11': names_day = 'Janika, Janita, Janina, Janette'
        elif today == '16-11': names_day = 'Aarne, Aarno, Aarni'
        elif today == '17-11': names_day = 'Eino, Einari'
        elif today == '18-11': names_day = 'Tenho, Jousia'
        elif today == '19-11': names_day = 'Elisabet, Liisa, Eliisa, Elisa, Elise, Liisi'
        elif today == '20-11': names_day = 'Jalmari, Jari'
        elif today == '21-11': names_day = 'Hilma'
        elif today == '22-11': names_day = 'Silja, Selja'
        elif today == '23-11': names_day = 'Ismo'
        elif today == '24-11': names_day = 'Lempi, Lemmikki, Sivi'
        elif today == '25-11': names_day = 'Katri, Kaisa, Kaija, Katja, Kaarina, Katariina, Katriina, Kati, Kaisu, Riina'
        elif today == '26-11': names_day = 'Sisko'
        elif today == '27-11': names_day = 'Hilkka'
        elif today == '28-11': names_day = 'Heini'
        elif today == '29-11': names_day = 'Aimo'
        elif today == '30-11': names_day = 'Antti, Antero, Atte'

    elif month == '12':
        if today == '01-12': names_day = 'Oskari'
        elif today == '02-12': names_day = 'Anelma, Unelma'
        elif today == '03-12': names_day = 'Vellamo, Meri'
        elif today == '04-12': names_day = 'Airi, Aira'
        elif today == '05-12': names_day = 'Selma'
        elif today == '06-12': names_day = 'Niilo, Nikolai, Niko, Niklas'
        elif today == '07-12': names_day = 'Sampsa'
        elif today == '08-12': names_day = 'Kyllikki, Kylli'
        elif today == '09-12': names_day = 'Anna, Anne, Anni, Anu, Annikki, Anneli, Annukka, Annika'
        elif today == '10-12': names_day = 'Jutta'
        elif today == '11-12': names_day = 'Taneli, Tatu, Daniel'
        elif today == '12-12': names_day = 'Tuovi'
        elif today == '13-12': names_day = 'Seija'
        elif today == '14-12': names_day = 'Jouko'
        elif today == '15-12': names_day = 'Heimo'
        elif today == '16-12': names_day = 'Auli, Aulikki, Aada'
        elif today == '17-12': names_day = 'Raakel'
        elif today == '18-12': names_day = 'Aapo, Aappo, Rami'
        elif today == '19-12': names_day = 'Iikka, Iiro, Iisakki, Isko'
        elif today == '20-12': names_day = 'Benjamin, Kerkko'
        elif today == '21-12': names_day = 'Tuomas, Tuomo, Tommi, Tomi'
        elif today == '22-12': names_day = 'Raafael'
        elif today == '23-12': names_day = 'Senni'
        elif today == '24-12': names_day = 'Aatami, Eeva, Eevi, Eveliina'
        elif today == '25-12': names_day = 'Joulup&auml;iv&auml;'
        elif today == '26-12': names_day = 'Tapani, Teppo, Tahvo'
        elif today == '27-12': names_day = 'Hannu, Hannes'
        elif today == '28-12': names_day = 'Piia'
        elif today == '29-12': names_day = 'Rauha'
        elif today == '30-12': names_day = 'Daavid, Taavetti, Taavi'
        elif today == '31-12': names_day = 'Sylvester, Silvo'
    
    return names_day