    <table border="0" cellspacing="0" cellpadding="0" width="180" id="navigation">
    <tr><td><a href="#" class="navText">Etusivu</a></td></tr>
    <tr><td><a href="#" class="navText">Verkkolehti</a></td></tr>
    <tr><td><a href="#" class="navText">Kuvagalleria</a></td></tr>
    <tr><td><a href="#" class="navText">Keskustele</a></td></tr>
    <tr><td><a href="#" class="navText">Vaikuta</a></td></tr>
    <tr><td><a href="#" class="navText">Apua ongelmiin</a></td></tr>
    <tr><td><a href="#" class="navText">Tuotteet</a></td></tr>
    <tr><td><a href="#" class="navText">Yhdistys</a></td></tr>
    </table>
    <p><img src="/media/img/flags/flag_{{ lang }}_60.gif"</p>

