    <ul>
      <li><a href="/specs/{{ lang }}/{{ profile }}/{{ event }}/frontpg/etusivu/" id="etusivuLink">Etusivu</a></li>
      <li><a href="/specs/{{ lang }}/{{ profile }}/{{ event }}/frontpg/verkkolehti/" id="verkkolehtiLink">Vaatteet</a></li>
      <li><a href="/specs/{{ lang }}/{{ profile }}/{{ event }}/frontpg/kuvagalleria/" id="kuvagalleriaLink">Keng&auml;t</a></li>
      <li><a href="/specs/{{ lang }}/{{ profile }}/{{ event }}/frontpg/keskustele/" id="keskusteleLink">Asusteet</a></li>
      <li><a href="/specs/{{ lang }}/{{ profile }}/{{ event }}/frontpg/tuotteet/" id="tuotteetLink">Pukeutumisopas</a></li>
      <li><a href="/specs/{{ lang }}/{{ profile }}/{{ event }}/frontpg/tuotteet/" id="tuotteetLink">Tule k&auml;ym‰‰n</a></li>
    </ul>

